# *********************************************
# Execute development environment             *
# *********************************************
# By: jramirez@ortussolutions.com             *
#**********************************************

# https://docs.docker.com/engine/reference/commandline/compose/
# https://hub.docker.com/r/ortussolutions/commandbox

version: "3.7"
services:
  API:
    container_name: api
    image: ortussolutions/commandbox:lucee5-alpine
    environment:
      PORT: 62090
      ENVIRONMENT: development
    ports:
      - "8081:62090"
    expose:
      - "8081"
    volumes:
      - .:/app